// The /how/ walkthroughs: every step points at a clip that exists.
//
// The steps JSON is GENERATED by scripts/record/*.mjs, and a recorder sweeps
// its own role's old clips before it starts. A run that dies part way through
// therefore deletes clips it never replaces, and the page 404s on them --
// which is exactly what happened once, unnoticed, because nothing checked.
//
// Cheap guard, no Playwright: read the committed JSON, look for the files.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync, existsSync } from 'node:fs';

const STEPS = new URL('../public/how/steps/', import.meta.url);
const MEDIA = new URL('../public/how/media/', import.meta.url);

const roles = readdirSync(STEPS).filter((f) => f.endsWith('.json'));

test('there is a walkthrough for every role', () => {
  assert.deepEqual(roles.sort(),
    ['parent.json', 'student.json', 'teacher-manage.json', 'teacher-setup.json']);
});

for (const file of roles) {
  test(`${file}: every clip it names is on disk`, () => {
    const doc = JSON.parse(readFileSync(new URL(file, STEPS), 'utf8'));
    assert.ok(doc.steps?.length, 'a walkthrough with no steps is not one');

    const missing = [];
    for (const step of doc.steps) {
      // A step without a clip is legitimate -- some are text only. A step
      // naming one that is not there is not.
      for (const key of ['clip', 'clipDark']) {
        if (step[key] && !existsSync(new URL(step[key], MEDIA))) missing.push(step[key]);
      }
    }
    assert.deepEqual(missing, [], `re-run scripts/record/ for this role:\n  ${missing.join('\n  ')}`);
  });

  test(`${file}: a light clip has its dark twin`, () => {
    // The page swaps to the -dark variant on a dark theme. Recording one theme
    // and not the other leaves half the readers watching the old flow, which
    // is worse than a missing file because nothing looks broken.
    const doc = JSON.parse(readFileSync(new URL(file, STEPS), 'utf8'));
    const lonely = doc.steps
      .filter((s) => s.clip && !s.clipDark)
      .map((s) => s.clip);
    assert.deepEqual(lonely, [], `record THEME=dark for this role:\n  ${lonely.join('\n  ')}`);
  });
}
